### ISSUE TITLE
craft\helpers\Db::uidById(): Argument #2 ($id) must be of type int, array given in Hyper

### ISSUE THREAD

**Issue by DanielDarrenJones** [verbb/zen#25]
### Describe the bug

Getting the following error when trying to export which seems to be coming from Hyper, not sure what could be causing it though?

craft\helpers\Db::uidById(): Argument #2 ($id) must be of type int, array given, called in /Users/danieljones/Dev/rothschild-safaris/vendor/verbb/zen/src/fields/Hyper.php on line 37
/Users/danieljones/Dev/rothschild-safaris/vendor/craftcms/cms/src/helpers/Db.php:1407
/Users/danieljones/Dev/rothschild-safaris/vendor/verbb/zen/src/fields/Hyper.php:37

<img width="539" alt="Image" src="https://github.com/user-attachments/assets/548c3d7e-7477-43af-bc53-7b4cdf890604" />

### Craft CMS version

5.6.9.1

### Plugin version

2.0.4

### Multi-site?

No

**Comment by elivz** [comment]
I am seeing the same thing in my logs. Also a scattering of `Unable to record element action: “verbb\zen\helpers\Db::uidById(): Argument #2 ($id) must be of type int, null given`

**Comment by engram-design** [comment]
So the value for a Hyper field - even when an element - shouldn't ever be an array. I'm not _quite_ sure how that's happened, but I believe Hyper also normalizes that, and we should as well.

Fixed for the next release. To get this early, run `composer require verbb/zen:"dev-craft-5 as 2.0.4"`.

@elivz That's an interesting one. I've just added some more logging above to dive into the stack trace of that error, if this happens again that should give us more content with the above update.

**Comment by elivz** [comment]
Ok, deployed and here is an example stack trace:

```
web-1  | 2025-05-01 06:30:50 [web.ERROR] [verbb\zen\services\Elements::_onElementAction] Unable to record element action: “verbb\zen\helpers\Db::uidById(): Argument #2 ($id) must be of type int, null given, called in /var/www/html/vendor/verbb/zen/src/elements/Entry.php on line 69” /var/www/html/vendor/verbb/zen/src/helpers/Db.php:33. Trace: “#0 /var/www/html/vendor/verbb/zen/src/elements/Entry.php(69): verbb\zen\helpers\Db::uidById() #1 /var/www/html/vendor/verbb/zen/src/base/Element.php(241): verbb\zen\elements\Entry::defineSerializedElement() #2 /var/www/html/vendor/verbb/zen/src/services/Elements.php(200): verbb\zen\base\Element::getSerializedElement() #3 /var/www/html/vendor/verbb/zen/src/services/Elements.php(109): verbb\zen\services\Elements->_onElementAction() #4 [internal function]: verbb\zen\services\Elements->onDeleteElement() #5 /var/www/html/vendor/yiisoft/yii2/base/Event.php(312): call_user_func() #6 /var/www/html/vendor/yiisoft/yii2/base/Component.php(654): yii\base\Event::trigger() #7 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(2459): yii\base\Component->trigger() #8 /var/www/html/vendor/craftcms/cms/src/elements/NestedElementManager.php(968): craft\services\Elements->deleteElement() #9 /var/www/html/vendor/craftcms/cms/src/elements/NestedElementManager.php(1084): craft\elements\NestedElementManager->deleteOtherNestedElements() #10 /var/www/html/vendor/craftcms/cms/src/elements/NestedElementManager.php(677): craft\elements\NestedElementManager->duplicateNestedElements() #11 /var/www/html/vendor/craftcms/cms/src/fields/Matrix.php(1447): craft\elements\NestedElementManager->maintainNestedElements() #12 /var/www/html/vendor/craftcms/cms/src/base/Element.php(6462): craft\fields\Matrix->afterElementPropagate() #13 /var/www/html/vendor/craftcms/cms/src/elements/Entry.php(2854): craft\base\Element->afterPropagate() #14 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(2049): craft\elements\Entry->afterPropagate() #15 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(1251): craft\services\Elements->craft\services\{closure}() #16 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(1919): craft\services\Elements->ensureBulkOp() #17 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(1540): craft\services\Elements->duplicateElement() #18 /var/www/html/vendor/craftcms/cms/src/services/Drafts.php(322): craft\services\Elements->updateCanonicalElement() #19 /var/www/html/vendor/craftcms/cms/src/controllers/ElementsController.php(2059): craft\services\Drafts->applyDraft() #20 [internal function]: craft\controllers\ElementsController->actionApplyDraft() #21 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array() #22 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams() #23 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction() #24 /var/www/html/vendor/craftcms/cms/src/web/Application.php(361): yii\base\Module->runAction() #25 /var/www/html/vendor/craftcms/cms/src/web/Application.php(660): craft\web\Application->runAction() #26 /var/www/html/vendor/craftcms/cms/src/web/Application.php(323): craft\web\Application->_processActionRequest() #27 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest() #28 /var/www/html/public/index.php(15): yii\base\Application->run() #29 {main}” {"memory":52262840} 
web-1  | 2025-05-01 06:30:50 [web.ERROR] [verbb\zen\services\Elements::_onElementAction] Unable to record element action: “verbb\zen\helpers\Db::uidById(): Argument #2 ($id) must be of type int, null given, called in /var/www/html/vendor/verbb/zen/src/elements/Entry.php on line 69” /var/www/html/vendor/verbb/zen/src/helpers/Db.php:33. Trace: “#0 /var/www/html/vendor/verbb/zen/src/elements/Entry.php(69): verbb\zen\helpers\Db::uidById() #1 /var/www/html/vendor/verbb/zen/src/base/Element.php(241): verbb\zen\elements\Entry::defineSerializedElement() #2 /var/www/html/vendor/verbb/zen/src/services/Elements.php(200): verbb\zen\base\Element::getSerializedElement() #3 /var/www/html/vendor/verbb/zen/src/services/Elements.php(109): verbb\zen\services\Elements->_onElementAction() #4 [internal function]: verbb\zen\services\Elements->onDeleteElement() #5 /var/www/html/vendor/yiisoft/yii2/base/Event.php(312): call_user_func() #6 /var/www/html/vendor/yiisoft/yii2/base/Component.php(654): yii\base\Event::trigger() #7 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(2459): yii\base\Component->trigger() #8 /var/www/html/vendor/craftcms/cms/src/elements/NestedElementManager.php(1314): craft\services\Elements->deleteElement() #9 /var/www/html/vendor/craftcms/cms/src/fields/Matrix.php(1491): craft\elements\NestedElementManager->deleteNestedElements() #10 /var/www/html/vendor/craftcms/cms/src/base/Element.php(6480): craft\fields\Matrix->beforeElementDelete() #11 /var/www/html/vendor/craftcms/cms/src/elements/Entry.php(2867): craft\base\Element->beforeDelete() #12 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(2396): craft\elements\Entry->beforeDelete() #13 /var/www/html/vendor/craftcms/cms/src/services/Drafts.php(332): craft\services\Elements->deleteElement() #14 /var/www/html/vendor/craftcms/cms/src/controllers/ElementsController.php(2059): craft\services\Drafts->applyDraft() #15 [internal function]: craft\controllers\ElementsController->actionApplyDraft() #16 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array() #17 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams() #18 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction() #19 /var/www/html/vendor/craftcms/cms/src/web/Application.php(361): yii\base\Module->runAction() #20 /var/www/html/vendor/craftcms/cms/src/web/Application.php(660): craft\web\Application->runAction() #21 /var/www/html/vendor/craftcms/cms/src/web/Application.php(323): craft\web\Application->_processActionRequest() #22 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest() #23 /var/www/html/public/index.php(15): yii\base\Application->run() #24 {main}” {"memory":55060760} 
web-1  | 2025-05-01 06:30:50 [web.ERROR] [verbb\zen\services\Elements::_onElementAction] Unable to record element action: “verbb\zen\helpers\Db::uidById(): Argument #2 ($id) must be of type int, null given, called in /var/www/html/vendor/verbb/zen/src/elements/Entry.php on line 69” /var/www/html/vendor/verbb/zen/src/helpers/Db.php:33. Trace: “#0 /var/www/html/vendor/verbb/zen/src/elements/Entry.php(69): verbb\zen\helpers\Db::uidById() #1 /var/www/html/vendor/verbb/zen/src/base/Element.php(241): verbb\zen\elements\Entry::defineSerializedElement() #2 /var/www/html/vendor/verbb/zen/src/services/Elements.php(200): verbb\zen\base\Element::getSerializedElement() #3 /var/www/html/vendor/verbb/zen/src/services/Elements.php(109): verbb\zen\services\Elements->_onElementAction() #4 [internal function]: verbb\zen\services\Elements->onDeleteElement() #5 /var/www/html/vendor/yiisoft/yii2/base/Event.php(312): call_user_func() #6 /var/www/html/vendor/yiisoft/yii2/base/Component.php(654): yii\base\Event::trigger() #7 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(2459): yii\base\Component->trigger() #8 /var/www/html/vendor/craftcms/cms/src/elements/NestedElementManager.php(1314): craft\services\Elements->deleteElement() #9 /var/www/html/vendor/craftcms/cms/src/fields/Matrix.php(1491): craft\elements\NestedElementManager->deleteNestedElements() #10 /var/www/html/vendor/craftcms/cms/src/base/Element.php(6480): craft\fields\Matrix->beforeElementDelete() #11 /var/www/html/vendor/craftcms/cms/src/elements/Entry.php(2867): craft\base\Element->beforeDelete() #12 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(2396): craft\elements\Entry->beforeDelete() #13 /var/www/html/vendor/craftcms/cms/src/services/Drafts.php(332): craft\services\Elements->deleteElement() #14 /var/www/html/vendor/craftcms/cms/src/controllers/ElementsController.php(2059): craft\services\Drafts->applyDraft() #15 [internal function]: craft\controllers\ElementsController->actionApplyDraft() #16 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array() #17 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams() #18 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction() #19 /var/www/html/vendor/craftcms/cms/src/web/Application.php(361): yii\base\Module->runAction() #20 /var/www/html/vendor/craftcms/cms/src/web/Application.php(660): craft\web\Application->runAction() #21 /var/www/html/vendor/craftcms/cms/src/web/Application.php(323): craft\web\Application->_processActionRequest() #22 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest() #23 /var/www/html/public/index.php(15): yii\base\Application->run() #24 {main}” {"memory":55104808} 
web-1  | 2025-05-01 06:30:50 [web.ERROR] [verbb\zen\services\Elements::_onElementAction] Unable to record element action: “verbb\zen\helpers\Db::uidById(): Argument #2 ($id) must be of type int, null given, called in /var/www/html/vendor/verbb/zen/src/elements/Entry.php on line 69” /var/www/html/vendor/verbb/zen/src/helpers/Db.php:33. Trace: “#0 /var/www/html/vendor/verbb/zen/src/elements/Entry.php(69): verbb\zen\helpers\Db::uidById() #1 /var/www/html/vendor/verbb/zen/src/base/Element.php(241): verbb\zen\elements\Entry::defineSerializedElement() #2 /var/www/html/vendor/verbb/zen/src/services/Elements.php(200): verbb\zen\base\Element::getSerializedElement() #3 /var/www/html/vendor/verbb/zen/src/services/Elements.php(109): verbb\zen\services\Elements->_onElementAction() #4 [internal function]: verbb\zen\services\Elements->onDeleteElement() #5 /var/www/html/vendor/yiisoft/yii2/base/Event.php(312): call_user_func() #6 /var/www/html/vendor/yiisoft/yii2/base/Component.php(654): yii\base\Event::trigger() #7 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(2459): yii\base\Component->trigger() #8 /var/www/html/vendor/craftcms/cms/src/elements/NestedElementManager.php(1314): craft\services\Elements->deleteElement() #9 /var/www/html/vendor/craftcms/cms/src/fields/Matrix.php(1491): craft\elements\NestedElementManager->deleteNestedElements() #10 /var/www/html/vendor/craftcms/cms/src/base/Element.php(6480): craft\fields\Matrix->beforeElementDelete() #11 /var/www/html/vendor/craftcms/cms/src/elements/Entry.php(2867): craft\base\Element->beforeDelete() #12 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(2396): craft\elements\Entry->beforeDelete() #13 /var/www/html/vendor/craftcms/cms/src/services/Drafts.php(332): craft\services\Elements->deleteElement() #14 /var/www/html/vendor/craftcms/cms/src/controllers/ElementsController.php(2059): craft\services\Drafts->applyDraft() #15 [internal function]: craft\controllers\ElementsController->actionApplyDraft() #16 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array() #17 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams() #18 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction() #19 /var/www/html/vendor/craftcms/cms/src/web/Application.php(361): yii\base\Module->runAction() #20 /var/www/html/vendor/craftcms/cms/src/web/Application.php(660): craft\web\Application->runAction() #21 /var/www/html/vendor/craftcms/cms/src/web/Application.php(323): craft\web\Application->_processActionRequest() #22 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest() #23 /var/www/html/public/index.php(15): yii\base\Application->run() #24 {main}” {"memory":55074768} 
web-1  | 2025-05-01 06:30:50 [web.ERROR] [verbb\zen\services\Elements::_onElementAction] Unable to record element action: “verbb\zen\helpers\Db::uidById(): Argument #2 ($id) must be of type int, null given, called in /var/www/html/vendor/verbb/zen/src/elements/Entry.php on line 69” /var/www/html/vendor/verbb/zen/src/helpers/Db.php:33. Trace: “#0 /var/www/html/vendor/verbb/zen/src/elements/Entry.php(69): verbb\zen\helpers\Db::uidById() #1 /var/www/html/vendor/verbb/zen/src/base/Element.php(241): verbb\zen\elements\Entry::defineSerializedElement() #2 /var/www/html/vendor/verbb/zen/src/services/Elements.php(200): verbb\zen\base\Element::getSerializedElement() #3 /var/www/html/vendor/verbb/zen/src/services/Elements.php(109): verbb\zen\services\Elements->_onElementAction() #4 [internal function]: verbb\zen\services\Elements->onDeleteElement() #5 /var/www/html/vendor/yiisoft/yii2/base/Event.php(312): call_user_func() #6 /var/www/html/vendor/yiisoft/yii2/base/Component.php(654): yii\base\Event::trigger() #7 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(2459): yii\base\Component->trigger() #8 /var/www/html/vendor/craftcms/cms/src/elements/NestedElementManager.php(1314): craft\services\Elements->deleteElement() #9 /var/www/html/vendor/craftcms/cms/src/fields/Matrix.php(1491): craft\elements\NestedElementManager->deleteNestedElements() #10 /var/www/html/vendor/craftcms/cms/src/base/Element.php(6480): craft\fields\Matrix->beforeElementDelete() #11 /var/www/html/vendor/craftcms/cms/src/elements/Entry.php(2867): craft\base\Element->beforeDelete() #12 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(2396): craft\elements\Entry->beforeDelete() #13 /var/www/html/vendor/craftcms/cms/src/services/Drafts.php(332): craft\services\Elements->deleteElement() #14 /var/www/html/vendor/craftcms/cms/src/controllers/ElementsController.php(2059): craft\services\Drafts->applyDraft() #15 [internal function]: craft\controllers\ElementsController->actionApplyDraft() #16 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array() #17 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams() #18 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction() #19 /var/www/html/vendor/craftcms/cms/src/web/Application.php(361): yii\base\Module->runAction() #20 /var/www/html/vendor/craftcms/cms/src/web/Application.php(660): craft\web\Application->runAction() #21 /var/www/html/vendor/craftcms/cms/src/web/Application.php(323): craft\web\Application->_processActionRequest() #22 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest() #23 /var/www/html/public/index.php(15): yii\base\Application->run() #24 {main}” {"memory":55118016} 
web-1  | 2025-05-01 06:30:50 [web.ERROR] [yii\base\ErrorException:1] Allowed memory size of 2147483648 bytes exhausted (tried to allocate 69632 bytes) {"trace":["#0 [internal function]: yii\\base\\ErrorHandler->handleFatalError()","#1 {main}"],"memory":2120608448,"exception":"[object] (yii\\base\\ErrorException(code: 1): Allowed memory size of 2147483648 bytes exhausted (tried to allocate 69632 bytes) at /var/www/html/vendor/craftcms/cms/src/elements/db/ElementQuery.php:2545)"}
```

Whatever is going on, it is ending in an out-of-memory error. Something recursive, maybe? Let me know if there is anything else I can provide to help debug this.

**Comment by elivz** [comment]
An additional clue: this seems to only be happening when publishing a draft. So I suspect maybe it isn't correctly excluding the deletion event on drafts that are being published?

**Comment by engram-design** [comment]
Thanks for that log info, so something about that seems to point to the `sectionId` of an entry being `null`. But that makes send if you have Matrix in the mix in Craft 5, as Matrix Blocks are now Entries.

Fixed for the next release. To get this early, run `composer require verbb/zen:"dev-craft-5 as 2.0.5"`.

I wasn't able to track down the memory issue, but looking into it!

**Comment by elivz** [comment]
I installed the dev version but unfortunately am still getting timeouts when applying a draft. If I disable the plugin temporarily the save goes through immediately. I am not getting anything in the logs now though – just a gateway timeout.

**Comment by engram-design** [comment]
Thanks for letting me know about the timeout issue, strange. It might be down to your field setup, or possibly even something else about your project. I don't suppose you'd be willing to send through your database to `web@verbb.io` for me to take a look? If so, just let me know an example entry you're trying to save on your install.
