### ISSUE TITLE
Images not exporting from Neo blocks

### ISSUE THREAD

**Issue by jaydensmith** [verbb/zen#4]
### Describe the bug

Images don't export from Neo blocks,[removing the eager load fixes the export](https://github.com/verbb/zen/blob/8ba502d23cf34856559bb4ed6f5bff260e00cac6/src/services/Export.php#L100). It may apply to other relational fields too.

Also, once I had a valid export with images, it is failing to import. `normalizeValue` for the `RelationField` finds the assets via the UID, but it does not save for some reason.

### Craft CMS version

4.5.11.1

### Plugin version

1.0.1

### Multi-site?

No

**Comment by engram-design** [comment]
Ah, I believe the eager-loading map was incorrect for Neo fields.

Fixed for the next release. To get this early, run `composer require verbb/zen:"dev-craft-4 as 1.0.1"`.

**Comment by jaydensmith** [comment]
@engram-design seems like that fixed the export, the import still isn't working, though

**Comment by engram-design** [comment]
Ah, I did forget to actually submit a PR to Neo from my local fork, which would explain it. Chime in at https://github.com/spicywebau/craft-neo/pull/817

**Comment by engram-design** [comment]
Fixed in [1.0.2](https://github.com/verbb/zen/releases/tag/1.0.2) (pending Neo PR)
